name: StaticAnalysisCI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install pylint autopep8 bandit pytest
    
    - name: Create post_trace directory
      run: |
        mkdir -p post_trace

    - name: Run autopep8
      run: |
        autopep8 --in-place --aggressive --aggressive hw2_debugging.py

    - name: Run pylint for hw2 debugging
      run: |
        pylint hw2_debugging.py >> post_trace/pylint_hw2_debugging.txt

    - name: Run pylint for rand
      run: |
        pylint rand.py >> post_trace/pylint_rand.txt

    - name: Run bandit
      run: |
        bandit -r /workspaces/HW1/hw2_debugging.py

    - name: Run tests
      run: |
        pytest > test_results.txt